import { FileCode2 } from "lucide-react";

import type { Tool } from "@/config/tools";

export const htmlFormatter: Tool = {
  slug: "html-formatter",
  name: "HTML Formatter",
  category: "developer",
  description: "Beautify or minify HTML with consistent indentation.",
  keywords: ["html formatter", "html beautifier", "html minifier", "prettify html"],
  icon: FileCode2,
  processing: "client",
  status: "live",
  steps: [
    "Paste your HTML, however messy.",
    "Beautify to re-indent it, or minify to strip whitespace and comments for production.",
    "Copy or download the result. Content inside pre, textarea and script is left untouched.",
  ],
  notes: [
    "Formatting re-indents HTML so the nesting is visible. It parses the markup and prints it back with consistent indentation, so a page that has been minified or generated by a tool becomes readable without changing what it renders.",
    "Whitespace in HTML is significant in specific places, and the formatter respects them. Inside <pre>, <textarea> and <code> blocks, spaces and line breaks are rendered literally, so reformatting them would change the page. Inline elements are also whitespace-sensitive — a line break between two <span> elements renders as a space, which is why aggressive reformatting can shift a layout.",
    "Formatting is not validation. Well-indented HTML can still have unclosed tags, duplicate IDs or invalid nesting. Run it through a validator if correctness matters; use this to make it readable.",
  ],
  faq: [
    {
      question: "Will formatting change how my page renders?",
      answer: "In almost all cases no, and the formatter preserves whitespace inside pre, textarea and code where it is significant. Be aware that whitespace between inline elements does render as a space, so heavily reformatting inline-heavy markup can shift spacing very slightly.",
    },
    {
      question: "Can I format minified HTML?",
      answer: "Yes, that is the main use. Minified markup is parsed and re-indented so the structure becomes visible, which is how you make sense of generated or compressed output.",
    },
    {
      question: "Does the formatter check my HTML is valid?",
      answer: "No. It re-indents rather than validates. Well-formatted HTML can still have unclosed tags, duplicate IDs or invalid nesting — use a dedicated validator for correctness.",
    },
    {
      question: "What indentation should I use for HTML?",
      answer: "Two spaces is the most common convention and keeps deeply nested markup from running off the screen. Four is easier to scan in flatter documents. Consistency across the codebase matters more than the choice.",
    },
    {
      question: "Is my markup uploaded?",
      answer: "No. Parsing and formatting run in your browser, so unreleased page source or markup containing internal URLs stays local.",
    },
  ],
};
