import Link from "next/link";

export default function ColourFormatsGuide() {
  return (
    <>
      <p>
        <code>#3b82f6</code>, <code>rgb(59 130 246)</code>,{" "}
        <code>hsl(217 91% 60%)</code> and <code>oklch(0.62 0.19 259)</code> are
        all the same blue. They differ in what they let you do with it — and one
        of them fixes a problem the others have had for decades.
      </p>

      <h2>HEX and RGB are the same thing</h2>
      <p>
        Both say how much red, green and blue to mix. HEX writes each channel as
        two hexadecimal digits from <code>00</code> to <code>ff</code>; RGB
        writes the same numbers in decimal, 0 to 255. <code>#ff0000</code> and{" "}
        <code>rgb(255 0 0)</code> are identical instructions.
      </p>
      <p>
        HEX is compact and pastes cleanly between design tools. RGB is readable
        and takes an alpha channel naturally. Neither is better; pick one and be
        consistent.
      </p>
      <p>
        The trouble with both is that the numbers do not correspond to anything
        you can reason about. Make this blue 20% lighter — which of the three
        numbers do you change, and by how much? There is no answer, which is why
        adjusting colour in HEX means guessing and re-checking.
      </p>

      <h2>HSL describes colour the way people do</h2>
      <p>Three numbers that each mean something:</p>
      <ul>
        <li><strong>Hue</strong> — 0 to 360 degrees around a colour wheel. Red 0, green 120, blue 240.</li>
        <li><strong>Saturation</strong> — 0% grey, 100% fully vivid.</li>
        <li><strong>Lightness</strong> — 0% black, 100% white, 50% the pure hue.</li>
      </ul>
      <p>
        Now the questions have answers. A lighter version is the same colour with
        higher lightness. A muted version drops the saturation. A complementary
        colour is the hue plus 180. This is why HSL is what people reach for when
        building a palette.
      </p>

      <h3>Where HSL falls down</h3>
      <p>
        Its lightness number does not match perceived brightness.{" "}
        <code>hsl(60 100% 50%)</code> is yellow and{" "}
        <code>hsl(240 100% 50%)</code> is blue — same stated lightness, and the
        yellow is dazzling while the blue is nearly black.
      </p>
      <p>
        The consequence is practical: a palette generated by holding lightness
        constant and rotating hue produces swatches that look wildly uneven, and
        text contrast that passes on one and fails on another. Anyone who has
        built a colour scale in HSL has hit this and had to hand-correct it.
      </p>

      <h2>OKLCH fixes exactly that</h2>
      <p>
        OKLCH takes the same three ideas — lightness, chroma, hue — and defines
        them against how human vision actually works rather than against the
        maths of a monitor. Its lightness is <em>perceptual</em>: two colours with
        the same L look equally bright, whatever their hue.
      </p>
      <p>That makes several previously annoying things straightforward:</p>
      <ul>
        <li>A colour scale at even lightness steps genuinely looks even.</li>
        <li>Rotating hue at fixed lightness keeps contrast stable, so accessibility does not break for one brand colour.</li>
        <li>Blending two colours passes through sensible intermediates instead of the grey mud RGB interpolation produces.</li>
      </ul>
      <p>
        It also reaches colours that HEX and RGB cannot express at all — modern
        displays cover a wider gamut than sRGB, and OKLCH can address it.
      </p>
      <p>
        Browser support is now good across the board. This site&rsquo;s own
        palette is defined in OKLCH for these reasons.
      </p>

      <h2>Which to use</h2>
      <ul>
        <li><strong>Pasting a brand colour someone gave you</strong> — HEX. It is what they will send.</li>
        <li><strong>Needing transparency</strong> — RGB or HSL with an alpha value.</li>
        <li><strong>Building a palette or a set of shades</strong> — OKLCH, or HSL if you must, and check the result.</li>
        <li><strong>Doing anything where contrast matters</strong> — OKLCH, and then <Link href="/developer/contrast-checker">verify it</Link>.</li>
      </ul>
      <p>
        You can convert between all of them with the{" "}
        <Link href="/color/color-picker">colour picker</Link>, build a scale with
        the <Link href="/color/color-palette-generator">palette generator</Link>,
        and <Link href="/color/color-mixer">blend two colours</Link> to see the
        intermediates.
      </p>

      <h2>One thing worth checking regardless of format</h2>
      <p>
        Contrast is the accessibility requirement that gets missed most, and it
        is not a matter of taste — WCAG asks for a ratio of at least 4.5:1
        between body text and its background, and 3:1 for large text. Mid-grey on
        white fails. Light grey on white fails badly.
      </p>
      <p>
        It is also the one that is trivially checkable, so there is no reason to
        ship a page that fails it.{" "}
        <Link href="/developer/contrast-checker">Check a pair</Link> before you
        commit to it.
      </p>
    </>
  );
}
